## Group Hex ID, No "0x".
## Example: group_id = "55fdd55633c578c7f2fb3e299f3d3bc88f8a9908df448f032c1b5d29db91e8c4"
group_id = "0000000000000000000000000000000000000000000000000000000000000000"

## This will be random string, and you can change.
## if need use secret nonce or seed, it will be useful.
secret = "{}"

## If custom db storage path. uncomment it.
## Default is `$HOME`,  `./` when dev.
## Example: db_path = "./"
db_path = "./.tdn"

## Group Symbol Name.
## If also have group_id and group_symbol, config will use group_id.
## Example: group_symbol = "CypherLink"
group_symbol = "CypherLink"

## App Permission.
## If set true, it is permissioned, and only stable connection;
## if set false, it is permissionless, has stable connection and DHT(p2p) connection.
## Default is false.
## Suggest: if want a permissioned DApp, use `permission = false` and `only_stable_data = true`.
permission = false

## If only receive stable connection's data.
only_stable_data = false

## P2P listen address, default is 0.0.0.0:7364,  uncomment below to change.
p2p_addr = "0.0.0.0:7364"

## P2P transport include: quic, tcp, udt, rtp, default is quic.
p2p_default_transport = "quic"

## P2P bootstrap seed IPs.
## Example: p2p_blocklist = ["1.1.1.1:7364", "192.168.0.1:7364"]
p2p_bootstrap = []

## P2P Blocklist(IP),  uncomment below to change.
## Example: p2p_blocklist = ["1.1.1.1", "192.168.0.1"]
#p2p_blocklist = []

## P2P Allowlist(ID),  uncomment below to change.
## Example: p2p_allow_peer_list = [
##              "55fdd55633c578c7f2fb3e299f3d3bc88f8a9908df448f032c1b5d29db91e8c4",
##              "b9f86efea43016debe9436c2d98fa273789ee81b511bf623e16de0b4c83176a6",
##          ]
#p2p_allow_peer_list = []

## P2P Blocklist (ID),  uncomment below to change.
## Example: p2p_block_peer_list = [
##              "55fdd55633c578c7f2fb3e299f3d3bc88f8a9908df448f032c1b5d29db91e8c4",
##              "b9f86efea43016debe9436c2d98fa273789ee81b511bf623e16de0b4c83176a6",
##          ]
#p2p_block_peer_list = []

## RPC listen address, default is 127.0.0.1:8000, uncomment below to change.
## Example: rpc_addr = "127.0.0.1:8000"
rpc_addr = "127.0.0.1:8000"

## WS listen address, default closed. if need, uncomment below to change.
## Example: rpc_ws = "127.0.0.1:8080"
rpc_ws = "127.0.0.1:8080"

## RPC Service index html body. if has, set path, if not, comment it.
## Example: rpc_index = "/var/www/html/index.html"
#rpc_index = "/var/www/html/index.html"